### PR TITLE
Upgrade to Middleman 4

### PR DESCRIPTION
**Pull request by defeated**
refs #15

### CODE REVIEW

**Comment by defeated** [comment]
There is one failing spec around relative links that I've not been able to solve =/

```
cucumber features/alias.feature:20 # Scenario: Aliases should use relative paths if relative_links are enabled
```

cc @jagthedrummer

**Comment by hubertron** [comment]
It would be great to get this merged in if we can get the tests passaing. I'd prefer this approach then using S3 Console to manually do a hundred redirects.

**Comment by defeated** [comment]
closing in favor of #17

**Comment by jagthedrummer** [comment]
Sorry for the delay @hubertron and @defeated. Somehow this snuck past me and I didn't realize it was hanging out there. Looks like #17 might supersedes this one. I'll try to find some time over the next week to give it a look and get it merged.

**Pull request closed without merging**
