### PR TITLE
Relative paths & frontmatter / metadata

### PR DESCRIPTION
**Pull request by Tuckie**
Add support for relative paths. Fixes issue #7.  Also allows treating the aliased resource more like a true resource & reference any frontmatter or other metadata from the original.

### CODE REVIEW

**Comment by sman591** [comment]
:+1:

**Comment by jagthedrummer** [comment]
Looks great! Thanks, @Tuckie!

**Comment by jagthedrummer** [comment]
Version 0.0.12 is now on RubyGems.

**Comment by Tuckie** [comment]
Thanks for the merge!

**Pull request merged**
