### PR TITLE
Use JavaScript redirect to keep search and hash

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
I chose not to squash since I'm actually using this branch in another project, but I can do that if necessary.

**Comment by jagthedrummer** [comment]
Any idea how this affects SEO concerns? I know that the meta tag method looks like a 301 redirect to most search engines and preserves the "link juice". Having trouble finding info about what a JS redirect does in that regard.

**Comment by wagenet** [comment]
@jagthedrummer The meta tag is there the same as always. Crawlers that don't do JS should continue to handle that as before. It's possible (though I don't think likely) that JS enabled browsers would treat the `location.replace` as special, which would also be fine.

**Comment by jagthedrummer** [comment]
Sounds good. Sorry for the delay, I just got back from vacation.

**Comment by jagthedrummer** [comment]
I just pushed `middleman-alias-0.0.11.gem`, which contains this fix.

**Pull request merged**
